import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

import { ThemeProvider } from "./components/theme-provider";
import Header from "./components/header";


const myFont = localFont({
  src: '../public/fonts/DotGothic16-Regular.ttf',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      suppressHydrationWarning
    >
      <body className={`${myFont.className} min-h-full flex flex-col`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
